const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Sin,
		C3.Plugins.Mouse,
		C3.Plugins.Keyboard,
		C3.Behaviors.Bullet,
		C3.Plugins.Spritefont2,
		C3.Behaviors.scrollto,
		C3.Plugins.Text,
		C3.Plugins.Audio,
		C3.Behaviors.custom,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Audio.Acts.SetPlaybackRate,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Behaviors.custom.Acts.SetSpeed,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Text.Cnds.CompareText,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetHeight,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Cnds.CompareHeight,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.System.Acts.ResetEventVar,
		C3.Plugins.Audio.Cnds.OnEnded,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Exps.time,
		C3.Plugins.Keyboard.Cnds.OnAnyKey
	];
};
self.C3_JsPropNameTable = [
	{inicioBack: 0},
	{Senóide: 0},
	{inicioPlay: 0},
	{songsMenuBack: 0},
	{songsMenuPainel: 0},
	{lofiHiphopBack: 0},
	{lofiHiphopTrilha: 0},
	{wonBack: 0},
	{wonSongsmenu: 0},
	{wonPlayagain: 0},
	{wonPainel: 0},
	{failedPainel: 0},
	{failedBack: 0},
	{failedPlayagain: 0},
	{failedSongsmenu: 0},
	{songsMenuLofiHiphop: 0},
	{Mouse: 0},
	{Teclado: 0},
	{Projétil: 0},
	{lofiHiphopNota: 0},
	{CentrarEm: 0},
	{centraratela: 0},
	{botao1: 0},
	{botao2: 0},
	{botao3: 0},
	{Sprite: 0},
	{botao4: 0},
	{Sprite2: 0},
	{botao5: 0},
	{score: 0},
	{naoClikou: 0},
	{lofiHiphopBarrinha: 0},
	{lofiHiphopMedidor: 0},
	{Áudio: 0},
	{timeDaMusica: 0},
	{wonScore: 0},
	{teste: 0},
	{wonNoteshit: 0},
	{wonNotesmissed: 0},
	{wonOverstrums: 0},
	{songsMenuHighscore: 0},
	{pressAnyKeyBackground: 0},
	{pressAnyKeyBackground2: 0},
	{pressAnyKeypressAnyKey: 0},
	{Personalizado: 0},
	{trilha: 0},
	{Sprite3: 0},
	{trilhaBorda: 0},
	{pontos: 0},
	{songsMenuDificil: 0},
	{songsMenuMedio: 0},
	{songsMenuFacil: 0},
	{linha: 0},
	{Sprite4: 0},
	{errou1: 0},
	{errou2: 0},
	{errou3: 0},
	{errou4: 0},
	{errou5: 0},
	{songsMenuEasy: 0},
	{A: 0},
	{S: 0},
	{J: 0},
	{K: 0},
	{Texto: 0},
	{L: 0},
	{overStrums: 0},
	{notesHit: 0},
	{notesMissed: 0},
	{highScore: 0}
];

self.InstanceType = {
	inicioBack: class extends self.ISpriteInstance {},
	inicioPlay: class extends self.ISpriteInstance {},
	songsMenuBack: class extends self.ISpriteInstance {},
	songsMenuPainel: class extends self.ISpriteInstance {},
	lofiHiphopBack: class extends self.ISpriteInstance {},
	lofiHiphopTrilha: class extends self.ISpriteInstance {},
	wonBack: class extends self.ISpriteInstance {},
	wonSongsmenu: class extends self.ISpriteInstance {},
	wonPlayagain: class extends self.ISpriteInstance {},
	wonPainel: class extends self.ISpriteInstance {},
	failedPainel: class extends self.ISpriteInstance {},
	failedBack: class extends self.ISpriteInstance {},
	failedPlayagain: class extends self.ISpriteInstance {},
	failedSongsmenu: class extends self.ISpriteInstance {},
	songsMenuLofiHiphop: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Teclado: class extends self.IInstance {},
	lofiHiphopNota: class extends self.ISpriteInstance {},
	centraratela: class extends self.ISpriteFontInstance {},
	botao1: class extends self.ISpriteInstance {},
	botao2: class extends self.ISpriteInstance {},
	botao3: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	botao4: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	botao5: class extends self.ISpriteInstance {},
	score: class extends self.ITextInstance {},
	naoClikou: class extends self.ISpriteInstance {},
	lofiHiphopBarrinha: class extends self.ISpriteInstance {},
	lofiHiphopMedidor: class extends self.ISpriteInstance {},
	Áudio: class extends self.IInstance {},
	timeDaMusica: class extends self.ITextInstance {},
	wonScore: class extends self.ITextInstance {},
	teste: class extends self.ITextInstance {},
	wonNoteshit: class extends self.ITextInstance {},
	wonNotesmissed: class extends self.ITextInstance {},
	wonOverstrums: class extends self.ITextInstance {},
	songsMenuHighscore: class extends self.ITextInstance {},
	pressAnyKeyBackground: class extends self.ISpriteInstance {},
	pressAnyKeyBackground2: class extends self.ISpriteInstance {},
	pressAnyKeypressAnyKey: class extends self.ISpriteInstance {},
	trilha: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	trilhaBorda: class extends self.ISpriteInstance {},
	pontos: class extends self.ITextInstance {},
	songsMenuDificil: class extends self.ISpriteInstance {},
	songsMenuMedio: class extends self.ISpriteInstance {},
	songsMenuFacil: class extends self.ISpriteInstance {},
	linha: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	errou1: class extends self.ISpriteInstance {},
	errou2: class extends self.ISpriteInstance {},
	errou3: class extends self.ISpriteInstance {},
	errou4: class extends self.ISpriteInstance {},
	errou5: class extends self.ISpriteInstance {},
	songsMenuEasy: class extends self.ITextInstance {},
	A: class extends self.ITextInstance {},
	S: class extends self.ITextInstance {},
	J: class extends self.ITextInstance {},
	K: class extends self.ITextInstance {},
	Texto: class extends self.ITextInstance {},
	L: class extends self.ITextInstance {}
}