const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Keyboard,
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Plugins.TiledBg,
		C3.Plugins.video,
		C3.Plugins.Audio,
		C3.Behaviors.scrollto,
		C3.Behaviors.EightDir,
		C3.Behaviors.MoveTo,
		C3.Behaviors.LOS,
		C3.Plugins.Text,
		C3.Behaviors.Flash,
		C3.Behaviors.Fade,
		C3.Plugins.Tilemap,
		C3.Behaviors.Pin,
		C3.Plugins.DrawingCanvas,
		C3.Behaviors.Persist,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.video.Acts.Play,
		C3.Plugins.video.Acts.Pause,
		C3.Plugins.video.Cnds.HasEnded,
		C3.Plugins.video.Acts.Destroy,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Text.Acts.TypewriterText,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Audio.Acts.Stop,
		C3.Behaviors.LOS.Cnds.HasLOSToObject,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Behaviors.scrollto.Acts.Shake,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Exps.Opacity,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.System.Acts.AddVar,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.Text.Acts.SetOpacity,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Exps.ColorValue,
		C3.Plugins.TiledBg.Exps.ColorValue,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.EightDir.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Behaviors.EightDir.Cnds.IsEnabled,
		C3.Plugins.Sprite.Cnds.IsOutsideLayout,
		C3.Behaviors.EightDir.Acts.SetMaxSpeed,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.TiledBg.Cnds.IsOnScreen,
		C3.Plugins.Audio.Acts.SetLooping,
		C3.Plugins.Text.Acts.SetPos,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Behaviors.LOS.Acts.SetRange,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.BBoxBottom,
		C3.Plugins.System.Acts.SortZOrderByInstVar,
		C3.Plugins.Text.Acts.MoveToTop,
		C3.Plugins.Sprite.Acts.ZMoveToObject,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.DrawingCanvas.Acts.SetDefaultColor,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.DrawingCanvas.Acts.PasteObject,
		C3.Plugins.DrawingCanvas.Acts.SetResolutionMode,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.Sprite.Exps.Height,
		C3.Behaviors.EightDir.Acts.SetEnabled,
		C3.Behaviors.scrollto.Acts.SetEnabled,
		C3.Behaviors.MoveTo.Acts.Stop,
		C3.Behaviors.solid.Acts.SetEnabled,
		C3.Behaviors.MoveTo.Acts.MoveToPosition,
		C3.Plugins.Sprite.Cnds.IsMirrored,
		C3.Behaviors.MoveTo.Acts.MoveToObject,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Text.Cnds.IsVisible,
		C3.Plugins.System.Acts.SubVar,
		C3.Behaviors.MoveTo.Cnds.IsEnabled,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Behaviors.Flash.Acts.StopFlashing,
		C3.Plugins.Tilemap.Cnds.IsVisible,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.System.Exps.rgba,
		C3.Plugins.TiledBg.Acts.SetDefaultColor,
		C3.Plugins.Tilemap.Acts.SetDefaultColor,
		C3.Plugins.Text.Acts.SetFontColor,
		C3.Plugins.Keyboard.Cnds.OnAnyKey,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Behaviors.Fade.Cnds.OnFadeOutEnd,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Behaviors.MoveTo.Cnds.OnArrived,
		C3.Behaviors.MoveTo.Acts.SetSpeed
	];
};
self.C3_JsPropNameTable = [
	{Teclado: 0},
	{PosY: 0},
	{Sólido: 0},
	{cama: 0},
	{fundo1: 0},
	{tpgalpao: 0},
	{Vídeo: 0},
	{Vídeo3: 0},
	{Áudio: 0},
	{CentrarEm: 0},
	{"8Direções": 0},
	{player: 0},
	{MoverPara: 0},
	{CampoDeVisão: 0},
	{inimigo1: 0},
	{robozin: 0},
	{timerfreze: 0},
	{alerta: 0},
	{save: 0},
	{Sprite: 0},
	{Piscar: 0},
	{tutorial: 0},
	{Esmaecer: 0},
	{Sprite2: 0},
	{Mosaico: 0},
	{nomejg: 0},
	{Fixar: 0},
	{player2: 0},
	{Texto2: 0},
	{Texto3: 0},
	{Texto4: 0},
	{Sprite4: 0},
	{Texto5: 0},
	{Mosaico2: 0},
	{Sprite5: 0},
	{Sprite6: 0},
	{portalado: 0},
	{portalado2: 0},
	{dialogo: 0},
	{Sprite3: 0},
	{Sprite7: 0},
	{Sprite8: 0},
	{Sprite9: 0},
	{Sprite10: 0},
	{Sprite11: 0},
	{Sprite12: 0},
	{Sprite13: 0},
	{alertxt: 0},
	{dialogorobo: 0},
	{Sprite14: 0},
	{Sprite15: 0},
	{Sprite16: 0},
	{Sprite17: 0},
	{Sprite18: 0},
	{Sprite19: 0},
	{Sprite20: 0},
	{Sprite21: 0},
	{Sprite22: 0},
	{Sprite23: 0},
	{Sprite24: 0},
	{Sprite25: 0},
	{portalado3: 0},
	{Sprite26: 0},
	{Sprite27: 0},
	{Texto6: 0},
	{livroAberto: 0},
	{portacasa: 0},
	{portacasa2: 0},
	{Texto7: 0},
	{Sprite28: 0},
	{Texto8: 0},
	{Sprite29: 0},
	{paused: 0},
	{Sprite30: 0},
	{cooldown: 0},
	{Sprite31: 0},
	{Sprite32: 0},
	{Sprite33: 0},
	{Sprite34: 0},
	{portalado4: 0},
	{Sprite35: 0},
	{Sprite36: 0},
	{Sprite37: 0},
	{Sprite38: 0},
	{Sprite39: 0},
	{Sprite40: 0},
	{Sprite41: 0},
	{Sprite42: 0},
	{Sprite43: 0},
	{Sprite44: 0},
	{Sprite45: 0},
	{Sprite46: 0},
	{Sprite47: 0},
	{Sprite48: 0},
	{Sprite49: 0},
	{Sprite50: 0},
	{Sprite51: 0},
	{Sprite52: 0},
	{Sprite53: 0},
	{Sprite54: 0},
	{Sprite55: 0},
	{Sprite56: 0},
	{Sprite57: 0},
	{minimapa: 0},
	{ponteiro: 0},
	{Persistir: 0},
	{TelaDeDesenho: 0},
	{ponteiro2: 0},
	{minimapa2: 0},
	{PlanoDeFundoEmBlocos: 0},
	{Sprite58: 0},
	{Vídeo2: 0},
	{Sprite59: 0},
	{Sprite60: 0},
	{Sprite61: 0},
	{Sprite62: 0},
	{Sprite63: 0},
	{Sprite64: 0},
	{Texto9: 0},
	{Sprite65: 0},
	{inimigo2: 0},
	{Sprite66: 0},
	{Sprite67: 0},
	{Sprite68: 0},
	{Sprite69: 0},
	{dialogo2: 0},
	{Sprite70: 0},
	{Sprite71: 0},
	{Sprite72: 0},
	{Texto: 0},
	{MoverPara2: 0},
	{CampoDeVisão2: 0},
	{Perseguidores: 0},
	{textura: 0},
	{textura2: 0},
	{morteInicial: 0},
	{morteInicial2: 0},
	{comeco: 0},
	{opacidade: 0},
	{tuto: 0},
	{DASH: 0},
	{cor: 0},
	{cor2: 0},
	{shift: 0},
	{musica: 0},
	{robosegue: 0},
	{mapa1: 0},
	{robot: 0},
	{chip: 0},
	{freeze: 0},
	{timer: 0},
	{cooldownPause: 0},
	{cooldownP: 0},
	{CheckpointX: 0},
	{CheckpointY: 0},
	{Trocar: 0},
	{dorm: 0},
	{alarm: 0},
	{dep: 0},
	{monocromo: 0},
	{Log: 0},
	{casa1: 0},
	{pause: 0},
	{Fcasa: 0},
	{Mapa: 0},
	{machine: 0},
	{machine2: 0},
	{Mach: 0},
	{Mach2: 0},
	{CONTROL: 0},
	{cutfinal: 0},
	{egg: 0}
];

self.InstanceType = {
	Teclado: class extends self.IInstance {},
	cama: class extends self.ISpriteInstance {},
	fundo1: class extends self.ITiledBackgroundInstance {},
	tpgalpao: class extends self.ISpriteInstance {},
	Vídeo: class extends self.IWorldInstance {},
	Vídeo3: class extends self.IWorldInstance {},
	Áudio: class extends self.IInstance {},
	player: class extends self.ISpriteInstance {},
	inimigo1: class extends self.ISpriteInstance {},
	robozin: class extends self.ISpriteInstance {},
	timerfreze: class extends self.ITextInstance {},
	alerta: class extends self.ISpriteInstance {},
	save: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	tutorial: class extends self.IWorldInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Mosaico: class extends self.ITilemapInstance {},
	nomejg: class extends self.ITextInstance {},
	player2: class extends self.ISpriteInstance {},
	Texto2: class extends self.ITextInstance {},
	Texto3: class extends self.ITextInstance {},
	Texto4: class extends self.ITextInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Texto5: class extends self.ITextInstance {},
	Mosaico2: class extends self.ITilemapInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	portalado: class extends self.ISpriteInstance {},
	portalado2: class extends self.ISpriteInstance {},
	dialogo: class extends self.ITextInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	alertxt: class extends self.ITextInstance {},
	dialogorobo: class extends self.ITextInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	Sprite17: class extends self.ISpriteInstance {},
	Sprite18: class extends self.ISpriteInstance {},
	Sprite19: class extends self.ISpriteInstance {},
	Sprite20: class extends self.ISpriteInstance {},
	Sprite21: class extends self.ISpriteInstance {},
	Sprite22: class extends self.ISpriteInstance {},
	Sprite23: class extends self.ISpriteInstance {},
	Sprite24: class extends self.ISpriteInstance {},
	Sprite25: class extends self.ISpriteInstance {},
	portalado3: class extends self.ISpriteInstance {},
	Sprite26: class extends self.ISpriteInstance {},
	Sprite27: class extends self.ISpriteInstance {},
	Texto6: class extends self.ITextInstance {},
	livroAberto: class extends self.ISpriteInstance {},
	portacasa: class extends self.ISpriteInstance {},
	portacasa2: class extends self.ISpriteInstance {},
	Texto7: class extends self.ITextInstance {},
	Sprite28: class extends self.ISpriteInstance {},
	Texto8: class extends self.ITextInstance {},
	Sprite29: class extends self.ISpriteInstance {},
	paused: class extends self.ITextInstance {},
	Sprite30: class extends self.ISpriteInstance {},
	cooldown: class extends self.ITextInstance {},
	Sprite31: class extends self.ISpriteInstance {},
	Sprite32: class extends self.ISpriteInstance {},
	Sprite33: class extends self.ISpriteInstance {},
	Sprite34: class extends self.ISpriteInstance {},
	portalado4: class extends self.ISpriteInstance {},
	Sprite35: class extends self.ISpriteInstance {},
	Sprite36: class extends self.ISpriteInstance {},
	Sprite37: class extends self.ISpriteInstance {},
	Sprite38: class extends self.ISpriteInstance {},
	Sprite39: class extends self.ISpriteInstance {},
	Sprite40: class extends self.ISpriteInstance {},
	Sprite41: class extends self.ISpriteInstance {},
	Sprite42: class extends self.ISpriteInstance {},
	Sprite43: class extends self.ISpriteInstance {},
	Sprite44: class extends self.ISpriteInstance {},
	Sprite45: class extends self.ISpriteInstance {},
	Sprite46: class extends self.ISpriteInstance {},
	Sprite47: class extends self.ISpriteInstance {},
	Sprite48: class extends self.ISpriteInstance {},
	Sprite49: class extends self.ISpriteInstance {},
	Sprite50: class extends self.ISpriteInstance {},
	Sprite51: class extends self.ISpriteInstance {},
	Sprite52: class extends self.ISpriteInstance {},
	Sprite53: class extends self.ISpriteInstance {},
	Sprite54: class extends self.ISpriteInstance {},
	Sprite55: class extends self.ISpriteInstance {},
	Sprite56: class extends self.ISpriteInstance {},
	Sprite57: class extends self.ISpriteInstance {},
	minimapa: class extends self.ISpriteInstance {},
	ponteiro: class extends self.ISpriteInstance {},
	TelaDeDesenho: class extends self.IDrawingCanvasInstance {},
	ponteiro2: class extends self.ISpriteInstance {},
	minimapa2: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos: class extends self.ITiledBackgroundInstance {},
	Sprite58: class extends self.ISpriteInstance {},
	Vídeo2: class extends self.IWorldInstance {},
	Sprite59: class extends self.ISpriteInstance {},
	Sprite60: class extends self.ISpriteInstance {},
	Sprite61: class extends self.ISpriteInstance {},
	Sprite62: class extends self.ISpriteInstance {},
	Sprite63: class extends self.ISpriteInstance {},
	Sprite64: class extends self.ISpriteInstance {},
	Texto9: class extends self.ITextInstance {},
	Sprite65: class extends self.ISpriteInstance {},
	inimigo2: class extends self.ISpriteInstance {},
	Sprite66: class extends self.ISpriteInstance {},
	Sprite67: class extends self.ISpriteInstance {},
	Sprite68: class extends self.ISpriteInstance {},
	Sprite69: class extends self.ISpriteInstance {},
	dialogo2: class extends self.ITextInstance {},
	Sprite70: class extends self.ISpriteInstance {},
	Sprite71: class extends self.ISpriteInstance {},
	Sprite72: class extends self.ISpriteInstance {},
	Texto: class extends self.ITextInstance {},
	Perseguidores: class extends self.ISpriteInstance {},
	textura: class extends self.ISpriteInstance {},
	textura2: class extends self.ISpriteInstance {}
}