const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Plugins.Tilemap,
		C3.Behaviors.Platform,
		C3.Behaviors.Sin,
		C3.Plugins.Text,
		C3.Plugins.Mouse,
		C3.Plugins.Button,
		C3.Plugins.TextBox,
		C3.Behaviors.scrollto,
		C3.Plugins.Particles,
		C3.Behaviors.Pin,
		C3.Plugins.Keyboard,
		C3.Plugins.Audio,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Plugins.Particles.Acts.SetPos,
		C3.Plugins.Particles.Acts.SetPosToObject,
		C3.Plugins.System.Cnds.Compare,
		C3.Behaviors.Platform.Exps.VectorX,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Behaviors.Platform.Cnds.IsJumping,
		C3.Behaviors.Platform.Cnds.IsFalling,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Behaviors.solid.Acts.SetEnabled,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.System.Cnds.ForEach,
		C3.Behaviors.Sin.Exps.CyclePosition,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Plugins.System.Acts.AddVar,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.Text.Acts.SetFontColor,
		C3.Plugins.System.Acts.ResetEventVar
	];
};
self.C3_JsPropNameTable = [
	{Sprite: 0},
	{Sprite10: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{Sprite6: 0},
	{Sprite7: 0},
	{Sprite8: 0},
	{Sprite9: 0},
	{background1: 0},
	{Sólido: 0},
	{bloco1: 0},
	{bloco2: 0},
	{bushes: 0},
	{clouds: 0},
	{clouds2: 0},
	{clouds_mid_fc: 0},
	{clouds_mid_t_fc: 0},
	{grass: 0},
	{grassy_mountains_fc: 0},
	{grassy_mountains_fc2: 0},
	{sky: 0},
	{sky2: 0},
	{sky_fc: 0},
	{sky_fc2: 0},
	{smoke_fx: 0},
	{far_mountains_fc: 0},
	{hill: 0},
	{hills: 0},
	{trees: 0},
	{Sprite17: 0},
	{tilemap_camada: 0},
	{vegetacao_camada: 0},
	{arvores_camada: 0},
	{folhas: 0},
	{folhas2: 0},
	{Platform: 0},
	{Senóide: 0},
	{crow_enemy: 0},
	{crow_enemy_vertical: 0},
	{raposa: 0},
	{game_over: 0},
	{life_player: 0},
	{Mouse: 0},
	{novo_jogo_texto: 0},
	{points: 0},
	{quit_button: 0},
	{quit_game_text: 0},
	{TEX: 0},
	{Texto: 0},
	{Texto2: 0},
	{Texto3: 0},
	{legenda1: 0},
	{legenda2: 0},
	{legenda3: 0},
	{ScrollTo: 0},
	{camera: 0},
	{Particles: 0},
	{Sprite15: 0},
	{Sprite16: 0},
	{Sprite11: 0},
	{Sprite12: 0},
	{Sprite13: 0},
	{toggle: 0},
	{toggleInicial: 0},
	{next_toogle: 0},
	{cenouraebronze: 0},
	{cenouraebronze2: 0},
	{try_button: 0},
	{Sprite14: 0},
	{lastcheckpointX: 0},
	{lastcheckpointY: 0},
	{Plataforma: 0},
	{Fixar: 0},
	{rabbit: 0},
	{Teclado: 0},
	{Áudio: 0},
	{Sprite18: 0},
	{life_play: 0},
	{save_point: 0},
	{seletor1: 0},
	{seletor: 0}
];

self.InstanceType = {
	Sprite: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	background1: class extends self.ISpriteInstance {},
	bloco1: class extends self.ISpriteInstance {},
	bloco2: class extends self.ISpriteInstance {},
	bushes: class extends self.ISpriteInstance {},
	clouds: class extends self.ISpriteInstance {},
	clouds2: class extends self.ISpriteInstance {},
	clouds_mid_fc: class extends self.ISpriteInstance {},
	clouds_mid_t_fc: class extends self.ISpriteInstance {},
	grass: class extends self.ISpriteInstance {},
	grassy_mountains_fc: class extends self.ISpriteInstance {},
	grassy_mountains_fc2: class extends self.ISpriteInstance {},
	sky: class extends self.ISpriteInstance {},
	sky2: class extends self.ISpriteInstance {},
	sky_fc: class extends self.ISpriteInstance {},
	sky_fc2: class extends self.ISpriteInstance {},
	smoke_fx: class extends self.ISpriteInstance {},
	far_mountains_fc: class extends self.ISpriteInstance {},
	hill: class extends self.ISpriteInstance {},
	hills: class extends self.ISpriteInstance {},
	trees: class extends self.ISpriteInstance {},
	Sprite17: class extends self.ISpriteInstance {},
	tilemap_camada: class extends self.ITilemapInstance {},
	vegetacao_camada: class extends self.ITilemapInstance {},
	arvores_camada: class extends self.ITilemapInstance {},
	folhas: class extends self.ITilemapInstance {},
	folhas2: class extends self.ITilemapInstance {},
	crow_enemy: class extends self.ISpriteInstance {},
	crow_enemy_vertical: class extends self.ISpriteInstance {},
	raposa: class extends self.ISpriteInstance {},
	game_over: class extends self.ITextInstance {},
	life_player: class extends self.ITextInstance {},
	Mouse: class extends self.IInstance {},
	novo_jogo_texto: class extends self.ITextInstance {},
	points: class extends self.ITextInstance {},
	quit_button: class extends self.IButtonInstance {},
	quit_game_text: class extends self.ITextInstance {},
	TEX: class extends self.ITextInputInstance {},
	Texto: class extends self.ITextInstance {},
	Texto2: class extends self.ITextInstance {},
	Texto3: class extends self.ITextInstance {},
	legenda1: class extends self.ITextInstance {},
	legenda2: class extends self.ITextInstance {},
	legenda3: class extends self.ITextInstance {},
	camera: class extends self.ISpriteInstance {},
	Particles: class extends self.IParticlesInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	toggle: class extends self.ISpriteInstance {},
	toggleInicial: class extends self.ISpriteInstance {},
	next_toogle: class extends self.ISpriteInstance {},
	cenouraebronze: class extends self.ISpriteInstance {},
	cenouraebronze2: class extends self.ISpriteInstance {},
	try_button: class extends self.IButtonInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	rabbit: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	Áudio: class extends self.IInstance {},
	Sprite18: class extends self.ISpriteInstance {}
}