const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Tilemap,
		C3.Plugins.Sprite,
		C3.Behaviors.TileMovement,
		C3.Behaviors.scrollto,
		C3.Plugins.Keyboard,
		C3.Behaviors.solid,
		C3.Plugins.TiledBg,
		C3.Plugins.Text,
		C3.Behaviors.Pin,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Sprite.Cnds.OnFrameChanged,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Behaviors.TileMovement.Cnds.IsMoving,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Keyboard.Cnds.OnKey
	];
};
self.C3_JsPropNameTable = [
	{chão: 0},
	{MovimentoEmGrid: 0},
	{CentrarEm: 0},
	{personagem: 0},
	{Teclado: 0},
	{Sólido: 0},
	{Mosaico: 0},
	{telamenu: 0},
	{textomenu: 0},
	{Mosaico2: 0},
	{blocoInvisivel: 0},
	{texto: 0},
	{Mosaico4: 0},
	{Fixar: 0},
	{Sprite2: 0},
	{Sprite: 0},
	{Sprite3: 0},
	{chave: 0},
	{Sprite5: 0},
	{Sprite6: 0},
	{Sprite7: 0},
	{Texto2: 0},
	{Texto3: 0},
	{Sprite8: 0},
	{Texto4: 0},
	{sprite9: 0},
	{Sprite4: 0},
	{Mosaico3: 0},
	{Sprite10: 0},
	{Texto5: 0},
	{Sprite11: 0},
	{Sprite12: 0},
	{Sprite13: 0},
	{Sprite14: 0},
	{martelo: 0}
];

self.InstanceType = {
	chão: class extends self.ITilemapInstance {},
	personagem: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	Mosaico: class extends self.ITilemapInstance {},
	telamenu: class extends self.ITiledBackgroundInstance {},
	textomenu: class extends self.ITextInstance {},
	Mosaico2: class extends self.ITilemapInstance {},
	blocoInvisivel: class extends self.ITiledBackgroundInstance {},
	texto: class extends self.ITextInstance {},
	Mosaico4: class extends self.ITilemapInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	chave: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Texto2: class extends self.ITextInstance {},
	Texto3: class extends self.ITextInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Texto4: class extends self.ITextInstance {},
	sprite9: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Mosaico3: class extends self.ITilemapInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Texto5: class extends self.ITextInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Sprite14: class extends self.ISpriteInstance {}
}