const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.Pin,
		C3.Behaviors.scrollto,
		C3.Plugins.Keyboard,
		C3.Plugins.Tilemap,
		C3.Behaviors.solid,
		C3.Behaviors.Sin,
		C3.Plugins.Camera3D,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.System.Acts.ResetEventVar,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Cnds.Compare,
		C3.Behaviors.Platform.Exps.VectorX,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Behaviors.Platform.Cnds.IsJumping,
		C3.Behaviors.Platform.Cnds.IsFalling,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.System.Cnds.CompareBetween,
		C3.Behaviors.Sin.Exps.CyclePosition,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Acts.AddVar
	];
};
self.C3_JsPropNameTable = [
	{TelaDeJogo: 0},
	{Plataforma: 0},
	{Atrelar: 0},
	{pinguin: 0},
	{CentrarEm: 0},
	{Camera: 0},
	{Keyboard: 0},
	{Vida: 0},
	{PlayerControl: 0},
	{GameOver: 0},
	{Sim: 0},
	{Nao: 0},
	{seta: 0},
	{TelaInicial: 0},
	{seta2: 0},
	{PlanoDeFundoEmBlocos3: 0},
	{Sólido: 0},
	{Mosaico: 0},
	{Sprite: 0},
	{Sprite2: 0},
	{vida: 0},
	{Senóide: 0},
	{pegrande: 0},
	{Slimes: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{sprite_: 0},
	{Câmera3D: 0},
	{portal: 0},
	{PlanoDeFundoEmBlocos: 0},
	{opcao: 0},
	{opcao1: 0}
];

self.InstanceType = {
	TelaDeJogo: class extends self.ITiledBackgroundInstance {},
	pinguin: class extends self.ISpriteInstance {},
	Camera: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	Vida: class extends self.ISpriteInstance {},
	PlayerControl: class extends self.ISpriteInstance {},
	GameOver: class extends self.ISpriteInstance {},
	Sim: class extends self.ISpriteInstance {},
	Nao: class extends self.ISpriteInstance {},
	seta: class extends self.ISpriteInstance {},
	TelaInicial: class extends self.ISpriteInstance {},
	seta2: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos3: class extends self.ITiledBackgroundInstance {},
	Mosaico: class extends self.ITilemapInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	pegrande: class extends self.ISpriteInstance {},
	Slimes: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	sprite_: class extends self.ISpriteInstance {},
	Câmera3D: class extends self.IInstance {},
	portal: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos: class extends self.ITiledBackgroundInstance {}
}