const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Persist,
		C3.Behaviors.solid,
		C3.Behaviors.EightDir,
		C3.Plugins.TiledBg,
		C3.Behaviors.Tween,
		C3.Behaviors.Pin,
		C3.Plugins.Text,
		C3.Plugins.Mouse,
		C3.Plugins.Keyboard,
		C3.Plugins.Touch,
		C3.Plugins.Tilemap,
		C3.Plugins.Audio,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Mouse.Acts.SetCursor2,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.System.Acts.SetLayerInteractive,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Acts.WaitForSignal,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Text.Acts.TypewriterText,
		C3.Plugins.System.Acts.Wait,
		C3.Behaviors.EightDir.Cnds.IsMoving,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Plugins.System.Cnds.Else,
		C3.Behaviors.EightDir.Acts.SetSpeed,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.EightDir.Acts.SimulateControl,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.Mouse.Cnds.OnWheel,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.TiledBg.Cnds.CompareOpacity,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.System.Cnds.OnLayoutEnd,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Acts.ResetEventVar,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Text.Cnds.IsRunningTypewriterText,
		C3.Plugins.Text.Acts.TypewriterFinish,
		C3.Plugins.System.Acts.Signal
	];
};
self.C3_JsPropNameTable = [
	{cama: 0},
	{Persistir: 0},
	{estante_livro: 0},
	{Sólido: 0},
	{baú: 0},
	{luz: 0},
	{papeisParede: 0},
	{tapete: 0},
	{plantagrande: 0},
	{painelJanela: 0},
	{luzLetras: 0},
	{janela: 0},
	{escrivaninha: 0},
	{janela2: 0},
	{janela3: 0},
	{ralo: 0},
	{plantaflor: 0},
	{abajur: 0},
	{cadernoMesa: 0},
	{criadomudo: 0},
	{retrato: 0},
	{diplomaparede: 0},
	{janela1: 0},
	{temchavebau: 0},
	{direcao: 0},
	{interagirbaú: 0},
	{interagirdiário: 0},
	{latinha: 0},
	{latinhaNoLixo: 0},
	{"8Direções": 0},
	{personagem: 0},
	{porta: 0},
	{diario: 0},
	{chave_inv: 0},
	{diario_inv: 0},
	{LIVRO: 0},
	{hint01: 0},
	{hint02: 0},
	{tuto_icon: 0},
	{menu_button: 0},
	{tutorial: 0},
	{Tween: 0},
	{Fader: 0},
	{BookCloseUp: 0},
	{mesa: 0},
	{caixas: 0},
	{florPqna: 0},
	{livroschao: 0},
	{livrosMesa: 0},
	{malas: 0},
	{mesaVintage: 0},
	{poltronalado: 0},
	{pufe: 0},
	{tapeteFlor: 0},
	{escada: 0},
	{Fixar: 0},
	{botão: 0},
	{cutbau: 0},
	{cutdiario: 0},
	{puzzle_diario: 0},
	{scroll_down: 0},
	{voltar_menu: 0},
	{cutdiariofundo: 0},
	{textodiario: 0},
	{textolia: 0},
	{balaoF: 0},
	{alerta_quarto: 0},
	{img_credits: 0},
	{img_menu: 0},
	{Mouse: 0},
	{Teclado: 0},
	{Toque: 0},
	{paredeInvisivel: 0},
	{bordaCama: 0},
	{bordacama_dir: 0},
	{bordacama_esq: 0},
	{borda_paredesolida: 0},
	{id: 0},
	{scenetrigger: 0},
	{quadroPopup: 0},
	{font_newgame: 0},
	{fon_credits: 0},
	{font_opções: 0},
	{capitulo1: 0},
	{Sprite10: 0},
	{Sprite2: 0},
	{sensor_porta: 0},
	{paredeBanheiro: 0},
	{paredes: 0},
	{Sprite18: 0},
	{Mosaico: 0},
	{Sprite: 0},
	{Mosaico2: 0},
	{ID: 0},
	{Scenetrigger2: 0},
	{teleporte_creditos: 0},
	{modal_voltar_menu: 0},
	{botao_cancelar: 0},
	{botao_voltar_menu: 0},
	{latacookies: 0},
	{lataCookie: 0},
	{filmes: 0},
	{Sprite3: 0},
	{broche: 0},
	{Sprite5: 0},
	{Sprite4: 0},
	{textoBau: 0},
	{Texto: 0},
	{Sprite6: 0},
	{Sprite7: 0},
	{Sprite8: 0},
	{Sprite9: 0},
	{Sprite11: 0},
	{Sprite12: 0},
	{Sprite13: 0},
	{Áudio: 0},
	{Sprite14: 0},
	{Sprite16: 0},
	{chave_bau: 0},
	{bau_aberto: 0},
	{cut_diario: 0},
	{qtd_eventos: 0},
	{inputfocus: 0},
	{amimir: 0},
	{page: 0},
	{t: 0}
];

self.InstanceType = {
	cama: class extends self.ISpriteInstance {},
	estante_livro: class extends self.ISpriteInstance {},
	baú: class extends self.ISpriteInstance {},
	luz: class extends self.ISpriteInstance {},
	papeisParede: class extends self.ISpriteInstance {},
	tapete: class extends self.ISpriteInstance {},
	plantagrande: class extends self.ISpriteInstance {},
	painelJanela: class extends self.ISpriteInstance {},
	luzLetras: class extends self.ISpriteInstance {},
	janela: class extends self.ISpriteInstance {},
	escrivaninha: class extends self.ISpriteInstance {},
	janela2: class extends self.ISpriteInstance {},
	janela3: class extends self.ISpriteInstance {},
	ralo: class extends self.ISpriteInstance {},
	plantaflor: class extends self.ISpriteInstance {},
	abajur: class extends self.ISpriteInstance {},
	cadernoMesa: class extends self.ISpriteInstance {},
	criadomudo: class extends self.ISpriteInstance {},
	retrato: class extends self.ISpriteInstance {},
	diplomaparede: class extends self.ISpriteInstance {},
	janela1: class extends self.ISpriteInstance {},
	personagem: class extends self.ISpriteInstance {},
	porta: class extends self.ISpriteInstance {},
	diario: class extends self.ISpriteInstance {},
	chave_inv: class extends self.ISpriteInstance {},
	diario_inv: class extends self.ISpriteInstance {},
	LIVRO: class extends self.ISpriteInstance {},
	hint01: class extends self.ISpriteInstance {},
	hint02: class extends self.ISpriteInstance {},
	tuto_icon: class extends self.ISpriteInstance {},
	menu_button: class extends self.ISpriteInstance {},
	tutorial: class extends self.ISpriteInstance {},
	Fader: class extends self.ITiledBackgroundInstance {},
	BookCloseUp: class extends self.ISpriteInstance {},
	mesa: class extends self.ISpriteInstance {},
	caixas: class extends self.ISpriteInstance {},
	florPqna: class extends self.ISpriteInstance {},
	livroschao: class extends self.ISpriteInstance {},
	livrosMesa: class extends self.ISpriteInstance {},
	malas: class extends self.ISpriteInstance {},
	mesaVintage: class extends self.ISpriteInstance {},
	poltronalado: class extends self.ISpriteInstance {},
	pufe: class extends self.ISpriteInstance {},
	tapeteFlor: class extends self.ISpriteInstance {},
	escada: class extends self.ISpriteInstance {},
	botão: class extends self.ISpriteInstance {},
	cutbau: class extends self.ISpriteInstance {},
	cutdiario: class extends self.ISpriteInstance {},
	puzzle_diario: class extends self.ISpriteInstance {},
	scroll_down: class extends self.ISpriteInstance {},
	voltar_menu: class extends self.ISpriteInstance {},
	cutdiariofundo: class extends self.ISpriteInstance {},
	textodiario: class extends self.ITextInstance {},
	textolia: class extends self.ITextInstance {},
	balaoF: class extends self.ISpriteInstance {},
	alerta_quarto: class extends self.ITextInstance {},
	img_credits: class extends self.ISpriteInstance {},
	img_menu: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Teclado: class extends self.IInstance {},
	Toque: class extends self.IInstance {},
	paredeInvisivel: class extends self.ISpriteInstance {},
	bordaCama: class extends self.ISpriteInstance {},
	bordacama_dir: class extends self.ISpriteInstance {},
	bordacama_esq: class extends self.ISpriteInstance {},
	borda_paredesolida: class extends self.ISpriteInstance {},
	scenetrigger: class extends self.ISpriteInstance {},
	quadroPopup: class extends self.ISpriteInstance {},
	font_newgame: class extends self.ISpriteInstance {},
	fon_credits: class extends self.ISpriteInstance {},
	font_opções: class extends self.ISpriteInstance {},
	capitulo1: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	sensor_porta: class extends self.ISpriteInstance {},
	paredeBanheiro: class extends self.ISpriteInstance {},
	paredes: class extends self.ISpriteInstance {},
	Sprite18: class extends self.ISpriteInstance {},
	Mosaico: class extends self.ITilemapInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Mosaico2: class extends self.ITilemapInstance {},
	Scenetrigger2: class extends self.ISpriteInstance {},
	teleporte_creditos: class extends self.ISpriteInstance {},
	modal_voltar_menu: class extends self.ISpriteInstance {},
	botao_cancelar: class extends self.ISpriteInstance {},
	botao_voltar_menu: class extends self.ISpriteInstance {},
	latacookies: class extends self.ISpriteInstance {},
	lataCookie: class extends self.ISpriteInstance {},
	filmes: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	broche: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	textoBau: class extends self.ITextInstance {},
	Texto: class extends self.ITextInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Áudio: class extends self.IInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	Sprite16: class extends self.ISpriteInstance {}
}