const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.jumpthru,
		C3.Behaviors.solid,
		C3.Plugins.Text,
		C3.Plugins.TiledBg,
		C3.Plugins.Tilemap,
		C3.Behaviors.Sin,
		C3.Plugins.Keyboard,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Behaviors.bound,
		C3.Behaviors.Bullet,
		C3.Behaviors.Timer,
		C3.Behaviors.Flash,
		C3.Behaviors.Fade,
		C3.Plugins.Mouse,
		C3.Plugins.gamepad,
		C3.Behaviors.Follow,
		C3.Plugins.Audio,
		C3.Plugins.LocalStorage,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.System.Acts.ToggleBoolVar,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Text.Acts.TypewriterText,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.gamepad.Cnds.OnButtonUp,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.gamepad.Cnds.OnButtonDown,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.gamepad.Cnds.IsButtonDown,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.gamepad.Cnds.CompareAxis,
		C3.Plugins.Sprite.Cnds.IsMirrored,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Behaviors.Platform.Acts.FallThrough,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Behaviors.Platform.Cnds.IsJumping,
		C3.Behaviors.Timer.Cnds.IsTimerRunning,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Behaviors.Platform.Acts.SetIgnoreInput,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.System.Cnds.Else,
		C3.Behaviors.Platform.Acts.SetGravity,
		C3.Behaviors.Platform.Acts.SetVectorY,
		C3.Behaviors.Platform.Cnds.IsByWall,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Behaviors.Bullet.Cnds.CompareTravelled,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Behaviors.Bullet.Acts.SetDistanceTravelled,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.ResetEventVar,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Text.Cnds.IsRunningTypewriterText,
		C3.Plugins.Text.Acts.TypewriterFinish,
		C3.Behaviors.Platform.Cnds.IsFalling,
		C3.Plugins.System.Cnds.CompareBetween,
		C3.Behaviors.Sin.Exps.CyclePosition,
		C3.Behaviors.Platform.Acts.SetVectorX,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.System.Acts.SubVar,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Behaviors.jumpthru.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.Sprite.Cnds.IsOverlappingOffset,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Exps.dt,
		C3.Behaviors.solid.Acts.SetEnabled
	];
};
self.C3_JsPropNameTable = [
	{PularAtravés: 0},
	{Blocopassavel: 0},
	{Sólido: 0},
	{Chão: 0},
	{Estatrancada: 0},
	{Porta: 0},
	{sensorPorta: 0},
	{dicaporta: 0},
	{ColisaoCasa: 0},
	{FundoQuarto: 0},
	{chavenova: 0},
	{CdTPorta: 0},
	{portafechada: 0},
	{capivara: 0},
	{caixacapivara: 0},
	{FALACAPIVARA: 0},
	{E: 0},
	{ecapivara: 0},
	{eporta: 0},
	{BG10: 0},
	{BG8: 0},
	{BG9: 0},
	{BG7: 0},
	{BG6: 0},
	{EspinhosmosaicoF2: 0},
	{MosaicoF2: 0},
	{sapo: 0},
	{verti: 0},
	{hori: 0},
	{AbelhaG: 0},
	{abelhinha: 0},
	{joaninha: 0},
	{abelhinha2: 0},
	{botaodestruir: 0},
	{parededestruir: 0},
	{platsurgir: 0},
	{platparado: 0},
	{Senóide: 0},
	{livro: 0},
	{BG5: 0},
	{BG4: 0},
	{BG3: 0},
	{BG2: 0},
	{BG1: 0},
	{espinhos: 0},
	{sensorRua1: 0},
	{plat: 0},
	{alavanca: 0},
	{seuManoel: 0},
	{EspinhosmosaicoF1: 0},
	{MosaicoF1: 0},
	{casa: 0},
	{Falamanoel: 0},
	{entradabiblioteca: 0},
	{Sprite4: 0},
	{ealavanca: 0},
	{balaomanoel: 0},
	{emanuel: 0},
	{qalavanca: 0},
	{Biblioteca: 0},
	{paredebiblioteca: 0},
	{chaobiblioteca: 0},
	{falabibli: 0},
	{bibliotexto: 0},
	{bibliotexto2: 0},
	{bibliotexto3: 0},
	{saida: 0},
	{entrada: 0},
	{ebibli: 0},
	{entrad: 0},
	{esaida: 0},
	{fundobiblioteca: 0},
	{btn_ng: 0},
	{btn_opt: 0},
	{Sprite: 0},
	{Sprite2: 0},
	{textoagrdecimento: 0},
	{Sprite3: 0},
	{Sprite5: 0},
	{baina: 0},
	{Sprite6: 0},
	{beijaFlor: 0},
	{Teclado: 0},
	{temchavedoquarto: 0},
	{dashes: 0},
	{moeda: 0},
	{jasaiu: 0},
	{Plataforma: 0},
	{CentrarEm: 0},
	{RestritoAoLayout: 0},
	{Bullet: 0},
	{Timer: 0},
	{Piscar: 0},
	{Player: 0},
	{Fade: 0},
	{rastro: 0},
	{Mouse: 0},
	{Gamepad: 0},
	{Seguir: 0},
	{Barradevida: 0},
	{pega: 0},
	{moeda1: 0},
	{Áudio: 0},
	{tempo_ativo: 0},
	{ativa: 0},
	{tempo_d_retorno: 0},
	{ativar_retorno: 0},
	{plataforma: 0},
	{pontuacaoseiva: 0},
	{moedahud: 0},
	{ArmazenamentoLocal: 0},
	{FolhaQuebrante: 0},
	{checkpoint: 0},
	{entradadabiblioteca: 0},
	{macaco: 0},
	{totemsaveplat: 0},
	{monkay: 0},
	{passarinho: 0},
	{passarinhoamarlo: 0},
	{passaarinho2: 0},
	{passarinho3: 0},
	{Sprite7: 0},
	{Pegouchave: 0},
	{barradevida: 0},
	{checkpointX: 0},
	{checkpointY: 0},
	{checkpointmoeda: 0}
];

self.InstanceType = {
	Blocopassavel: class extends self.ISpriteInstance {},
	Chão: class extends self.ISpriteInstance {},
	Porta: class extends self.ISpriteInstance {},
	sensorPorta: class extends self.ISpriteInstance {},
	dicaporta: class extends self.ITextInstance {},
	ColisaoCasa: class extends self.ISpriteInstance {},
	FundoQuarto: class extends self.ISpriteInstance {},
	chavenova: class extends self.ISpriteInstance {},
	CdTPorta: class extends self.ISpriteInstance {},
	portafechada: class extends self.ITextInstance {},
	capivara: class extends self.ISpriteInstance {},
	caixacapivara: class extends self.ISpriteInstance {},
	FALACAPIVARA: class extends self.ITextInstance {},
	E: class extends self.ITextInstance {},
	ecapivara: class extends self.ISpriteInstance {},
	eporta: class extends self.ISpriteInstance {},
	BG10: class extends self.ITiledBackgroundInstance {},
	BG8: class extends self.ITiledBackgroundInstance {},
	BG9: class extends self.ITiledBackgroundInstance {},
	BG7: class extends self.ITiledBackgroundInstance {},
	BG6: class extends self.ITiledBackgroundInstance {},
	EspinhosmosaicoF2: class extends self.ITilemapInstance {},
	MosaicoF2: class extends self.ITilemapInstance {},
	sapo: class extends self.ISpriteInstance {},
	AbelhaG: class extends self.ISpriteInstance {},
	abelhinha: class extends self.ISpriteInstance {},
	joaninha: class extends self.ISpriteInstance {},
	abelhinha2: class extends self.ISpriteInstance {},
	botaodestruir: class extends self.ISpriteInstance {},
	parededestruir: class extends self.ISpriteInstance {},
	platsurgir: class extends self.ISpriteInstance {},
	platparado: class extends self.ISpriteInstance {},
	livro: class extends self.ISpriteInstance {},
	BG5: class extends self.ITiledBackgroundInstance {},
	BG4: class extends self.ITiledBackgroundInstance {},
	BG3: class extends self.ITiledBackgroundInstance {},
	BG2: class extends self.ITiledBackgroundInstance {},
	BG1: class extends self.ITiledBackgroundInstance {},
	espinhos: class extends self.ISpriteInstance {},
	sensorRua1: class extends self.ISpriteInstance {},
	plat: class extends self.ISpriteInstance {},
	alavanca: class extends self.ISpriteInstance {},
	seuManoel: class extends self.ISpriteInstance {},
	EspinhosmosaicoF1: class extends self.ITilemapInstance {},
	MosaicoF1: class extends self.ITilemapInstance {},
	casa: class extends self.ISpriteInstance {},
	Falamanoel: class extends self.ITextInstance {},
	entradabiblioteca: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	ealavanca: class extends self.ISpriteInstance {},
	balaomanoel: class extends self.ISpriteInstance {},
	emanuel: class extends self.ISpriteInstance {},
	qalavanca: class extends self.ISpriteInstance {},
	Biblioteca: class extends self.ISpriteInstance {},
	paredebiblioteca: class extends self.ISpriteInstance {},
	chaobiblioteca: class extends self.ISpriteInstance {},
	falabibli: class extends self.ISpriteInstance {},
	bibliotexto: class extends self.ITextInstance {},
	bibliotexto2: class extends self.ITextInstance {},
	bibliotexto3: class extends self.ITextInstance {},
	saida: class extends self.ISpriteInstance {},
	entrada: class extends self.ISpriteInstance {},
	ebibli: class extends self.ISpriteInstance {},
	entrad: class extends self.ISpriteInstance {},
	esaida: class extends self.ISpriteInstance {},
	fundobiblioteca: class extends self.ISpriteInstance {},
	btn_ng: class extends self.ISpriteInstance {},
	btn_opt: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	textoagrdecimento: class extends self.ITextInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	baina: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	beijaFlor: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	Player: class extends self.ISpriteInstance {},
	rastro: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Gamepad: class extends self.IInstance {},
	Barradevida: class extends self.ISpriteInstance {},
	moeda1: class extends self.ISpriteInstance {},
	Áudio: class extends self.IInstance {},
	plataforma: class extends self.ISpriteInstance {},
	pontuacaoseiva: class extends self.ITextInstance {},
	moedahud: class extends self.ISpriteInstance {},
	ArmazenamentoLocal: class extends self.IInstance {},
	FolhaQuebrante: class extends self.ISpriteInstance {},
	checkpoint: class extends self.ISpriteInstance {},
	entradadabiblioteca: class extends self.ISpriteInstance {},
	macaco: class extends self.ISpriteInstance {},
	totemsaveplat: class extends self.ISpriteInstance {},
	monkay: class extends self.ISpriteInstance {},
	passarinho: class extends self.ISpriteInstance {},
	passarinhoamarlo: class extends self.ISpriteInstance {},
	passaarinho2: class extends self.ISpriteInstance {},
	passarinho3: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {}
}