const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Behaviors.Flash,
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Behaviors.solid,
		C3.Plugins.Particles,
		C3.Behaviors.Sin,
		C3.Plugins.Text,
		C3.Plugins.Audio,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Keyboard.Cnds.OnKeyReleased,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.System.Cnds.Compare,
		C3.Behaviors.Sin.Exps.CyclePosition,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Acts.SubVar,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Acts.SetVisible
	];
};
self.C3_JsPropNameTable = [
	{cenario_menu: 0},
	{george: 0},
	{grama: 0},
	{plataforma: 0},
	{Plataforma: 0},
	{CentrarEm: 0},
	{Flash: 0},
	{player: 0},
	{Teclado: 0},
	{Mouse: 0},
	{Sólido: 0},
	{bloco: 0},
	{Partículas: 0},
	{morte_inimigo: 0},
	{Sine: 0},
	{Platform: 0},
	{aranha_olho: 0},
	{bau_fechado: 0},
	{pistas: 0},
	{cronometro: 0},
	{Titulo_inicio: 0},
	{Placarzerado: 0},
	{pistas_contagem: 0},
	{vidas: 0},
	{numero_vidas: 0},
	{muro: 0},
	{muro_derrota: 0},
	{frase_derrota: 0},
	{Play: 0},
	{Menu: 0},
	{menu_cenario: 0},
	{muto_vitoria: 0},
	{capa_menu: 0},
	{pistaAberta: 0},
	{charada_it: 0},
	{Solid: 0},
	{bau_animado: 0},
	{bau_derrota: 0},
	{Portal_entrada: 0},
	{desenho_vitoria: 0},
	{bau_inicio: 0},
	{frase_vitoria: 0},
	{somDeRisada: 0},
	{Opções: 0},
	{opcao: 0},
	{acao: 0},
	{Objetivo: 0},
	{opcao2: 0},
	{acao2: 0},
	{ComoJogar: 0},
	{opcao3: 0},
	{acao3: 0},
	{sair: 0},
	{Objetivo_instrucao: 0},
	{cmoJogar_instr: 0},
	{Sprite: 0},
	{Patati: 0},
	{Pennywise: 0},
	{Patata: 0},
	{estado: 0},
	{gerapistas: 0},
	{Vidas: 0},
	{Pistas: 0}
];

self.InstanceType = {
	cenario_menu: class extends self.ITiledBackgroundInstance {},
	george: class extends self.ISpriteInstance {},
	grama: class extends self.ITiledBackgroundInstance {},
	plataforma: class extends self.ITiledBackgroundInstance {},
	player: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	bloco: class extends self.ISpriteInstance {},
	Partículas: class extends self.IParticlesInstance {},
	morte_inimigo: class extends self.IParticlesInstance {},
	aranha_olho: class extends self.ISpriteInstance {},
	bau_fechado: class extends self.ISpriteInstance {},
	pistas: class extends self.ISpriteInstance {},
	cronometro: class extends self.ITextInstance {},
	Titulo_inicio: class extends self.ITextInstance {},
	Placarzerado: class extends self.ISpriteInstance {},
	pistas_contagem: class extends self.ITextInstance {},
	vidas: class extends self.ISpriteInstance {},
	numero_vidas: class extends self.ITextInstance {},
	muro: class extends self.ISpriteInstance {},
	muro_derrota: class extends self.ISpriteInstance {},
	frase_derrota: class extends self.ITextInstance {},
	Play: class extends self.ITextInstance {},
	Menu: class extends self.ITextInstance {},
	menu_cenario: class extends self.ISpriteInstance {},
	muto_vitoria: class extends self.ISpriteInstance {},
	capa_menu: class extends self.ISpriteInstance {},
	pistaAberta: class extends self.ISpriteInstance {},
	charada_it: class extends self.ITextInstance {},
	bau_animado: class extends self.ISpriteInstance {},
	bau_derrota: class extends self.ISpriteInstance {},
	Portal_entrada: class extends self.ISpriteInstance {},
	desenho_vitoria: class extends self.ISpriteInstance {},
	bau_inicio: class extends self.ISpriteInstance {},
	frase_vitoria: class extends self.ITextInstance {},
	somDeRisada: class extends self.IInstance {},
	Opções: class extends self.ITextInstance {},
	Objetivo: class extends self.ITextInstance {},
	ComoJogar: class extends self.ITextInstance {},
	sair: class extends self.ITextInstance {},
	Objetivo_instrucao: class extends self.ISpriteInstance {},
	cmoJogar_instr: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Patati: class extends self.ITextInstance {},
	Pennywise: class extends self.ITextInstance {},
	Patata: class extends self.ITextInstance {}
}