const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.Bullet,
		C3.Behaviors.Platform,
		C3.Behaviors.Flash,
		C3.Behaviors.scrollto,
		C3.Plugins.Keyboard,
		C3.Plugins.Tilemap,
		C3.Behaviors.jumpthru,
		C3.Behaviors.Sin,
		C3.Plugins.Text,
		C3.Behaviors.custom,
		C3.Plugins.Spritefont2,
		C3.Plugins.Camera3D,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.Platform.Cnds.IsJumping,
		C3.Behaviors.Platform.Cnds.IsFalling,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.ResetEventVar,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Behaviors.Platform.Cnds.OnLand,
		C3.Behaviors.Platform.Cnds.OnFall,
		C3.Behaviors.Platform.Cnds.OnStop,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Cnds.IsOutsideLayout,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Behaviors.Platform.Cnds.OnMove,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.Sprite.Cnds.IsBetweenAngles,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Behaviors.custom.Acts.AccelerateAngle,
		C3.Plugins.Sprite.Acts.AddRemoveAnimation,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Spritefont2.Acts.SetVisible,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Acts.SetPos
	];
};
self.C3_JsPropNameTable = [
	{background: 0},
	{nuvemMaior: 0},
	{nuvemMeio: 0},
	{nuvemMenor: 0},
	{Sólido: 0},
	{blocoSolido: 0},
	{Direcao_Dash: 0},
	{Ativo_Dash: 0},
	{Projétil: 0},
	{Plataforma: 0},
	{Piscar: 0},
	{CentrarEm: 0},
	{player: 0},
	{Teclado: 0},
	{terra: 0},
	{espinhoParede: 0},
	{espinhodireito: 0},
	{espinhoEsquerdo: 0},
	{PularAtravés: 0},
	{Senóide: 0},
	{plataforma: 0},
	{gaiola: 0},
	{suporteEsquerdocanhao: 0},
	{suporteEsquerdo: 0},
	{suporteDireito: 0},
	{Texto: 0},
	{canhao: 0},
	{bala: 0},
	{pularAtraves: 0},
	{plataformaSolida: 0},
	{chave: 0},
	{espinhoDuplo: 0},
	{espinhoEsq: 0},
	{espinhoPonta: 0},
	{espinhoParede2: 0},
	{suporteDireitoSprite: 0},
	{suporteGaiola: 0},
	{plataformaEquilibrio: 0},
	{obj1: 0},
	{obj3: 0},
	{obj2: 0},
	{Personalizado: 0},
	{plataformaQuebradica1: 0},
	{plataformaQuebradica2: 0},
	{plataformaQuebradica3: 0},
	{plataformaQuebradica4: 0},
	{plataformaQuebradica5: 0},
	{plataformaQuebradica6: 0},
	{plataformaQuebradica7: 0},
	{plataformaQuebradica8: 0},
	{plataformaQuebradica9: 0},
	{plataformaQuebradica10: 0},
	{plataformaQuebradica11: 0},
	{plataformaQuebradica12: 0},
	{obj5: 0},
	{obj7: 0},
	{plataformaEquilibrio2: 0},
	{obj6: 0},
	{ajuda: 0},
	{ararajuda: 0},
	{seguranca: 0},
	{parede: 0},
	{proximo: 0},
	{espinhoParede3: 0},
	{canhao2: 0},
	{bala2: 0},
	{Texto2: 0},
	{BGdialogo: 0},
	{Texto3: 0},
	{dialogo: 0},
	{placa: 0},
	{balao: 0},
	{fonte: 0},
	{visualLogo: 0},
	{balao3: 0},
	{balao2: 0},
	{BGdialogo2: 0},
	{fonte2: 0},
	{visualLogo2: 0},
	{balao4: 0},
	{fonte3: 0},
	{BGdialogo3: 0},
	{visualLogo3: 0},
	{balao5: 0},
	{BGdialogo4: 0},
	{fonte4: 0},
	{visualLogo4: 0},
	{balao6: 0},
	{BGdialogo5: 0},
	{visualLogo5: 0},
	{tutorialSuporte: 0},
	{fonte5: 0},
	{tutorialPlataforma: 0},
	{balao7: 0},
	{BGdialogo6: 0},
	{fonte6: 0},
	{visualLogo6: 0},
	{tutorialPlatquebrada: 0},
	{balao8: 0},
	{BGdialogo7: 0},
	{fonte7: 0},
	{visualLogo7: 0},
	{tutorialEquilibrio: 0},
	{balao9: 0},
	{BGdialogo8: 0},
	{fonte8: 0},
	{visualLogo8: 0},
	{balao10: 0},
	{BGdialogo9: 0},
	{fonte9: 0},
	{visualLogo9: 0},
	{Sprite: 0},
	{balao11: 0},
	{BGdialogo10: 0},
	{fonte10: 0},
	{visualLogo10: 0},
	{tutorialChave: 0},
	{tutorialAjuda: 0},
	{Câmera3D: 0},
	{coqueiro: 0},
	{coqueiroInvertido: 0},
	{Sprite2: 0},
	{mato: 0},
	{mato2: 0},
	{logo: 0},
	{logoArara: 0},
	{menu2: 0},
	{menu1: 0},
	{menu3: 0},
	{menu4: 0},
	{coqueiroInvertido2: 0},
	{Selecionar: 0},
	{araraNeymar: 0},
	{menuu: 0},
	{credito: 0},
	{FonteDeSprites: 0},
	{Sprite3: 0},
	{creditofinal: 0},
	{Sprite4: 0},
	{finaldefase: 0},
	{salvas: 0},
	{FonteDeSprites2: 0},
	{salvaCommortal: 0},
	{salvaFrenter: 0},
	{chavee: 0},
	{chaveee: 0},
	{chaave: 0},
	{selecionar: 0},
	{selecionar2: 0}
];

self.InstanceType = {
	background: class extends self.ISpriteInstance {},
	nuvemMaior: class extends self.ISpriteInstance {},
	nuvemMeio: class extends self.ISpriteInstance {},
	nuvemMenor: class extends self.ISpriteInstance {},
	blocoSolido: class extends self.ISpriteInstance {},
	player: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	terra: class extends self.ITilemapInstance {},
	espinhoParede: class extends self.ITilemapInstance {},
	espinhodireito: class extends self.ITilemapInstance {},
	espinhoEsquerdo: class extends self.ITilemapInstance {},
	plataforma: class extends self.ITilemapInstance {},
	gaiola: class extends self.ITilemapInstance {},
	suporteEsquerdocanhao: class extends self.ITilemapInstance {},
	suporteEsquerdo: class extends self.ITilemapInstance {},
	suporteDireito: class extends self.ITilemapInstance {},
	Texto: class extends self.ITextInstance {},
	canhao: class extends self.ISpriteInstance {},
	bala: class extends self.ISpriteInstance {},
	pularAtraves: class extends self.ISpriteInstance {},
	plataformaSolida: class extends self.ISpriteInstance {},
	chave: class extends self.ISpriteInstance {},
	espinhoDuplo: class extends self.ISpriteInstance {},
	espinhoEsq: class extends self.ISpriteInstance {},
	espinhoPonta: class extends self.ISpriteInstance {},
	espinhoParede2: class extends self.ISpriteInstance {},
	suporteDireitoSprite: class extends self.ISpriteInstance {},
	suporteGaiola: class extends self.ISpriteInstance {},
	plataformaEquilibrio: class extends self.ISpriteInstance {},
	obj1: class extends self.ISpriteInstance {},
	obj3: class extends self.ISpriteInstance {},
	obj2: class extends self.ISpriteInstance {},
	plataformaQuebradica1: class extends self.ISpriteInstance {},
	plataformaQuebradica2: class extends self.ISpriteInstance {},
	plataformaQuebradica3: class extends self.ISpriteInstance {},
	plataformaQuebradica4: class extends self.ISpriteInstance {},
	plataformaQuebradica5: class extends self.ISpriteInstance {},
	plataformaQuebradica6: class extends self.ISpriteInstance {},
	plataformaQuebradica7: class extends self.ISpriteInstance {},
	plataformaQuebradica8: class extends self.ISpriteInstance {},
	plataformaQuebradica9: class extends self.ISpriteInstance {},
	plataformaQuebradica10: class extends self.ISpriteInstance {},
	plataformaQuebradica11: class extends self.ISpriteInstance {},
	plataformaQuebradica12: class extends self.ISpriteInstance {},
	obj5: class extends self.ISpriteInstance {},
	obj7: class extends self.ISpriteInstance {},
	plataformaEquilibrio2: class extends self.ISpriteInstance {},
	obj6: class extends self.ISpriteInstance {},
	ajuda: class extends self.ISpriteInstance {},
	ararajuda: class extends self.ISpriteInstance {},
	seguranca: class extends self.ISpriteInstance {},
	parede: class extends self.ISpriteInstance {},
	proximo: class extends self.ISpriteInstance {},
	espinhoParede3: class extends self.ISpriteInstance {},
	canhao2: class extends self.ISpriteInstance {},
	bala2: class extends self.ISpriteInstance {},
	Texto2: class extends self.ITextInstance {},
	BGdialogo: class extends self.ISpriteInstance {},
	Texto3: class extends self.ITextInstance {},
	dialogo: class extends self.ITextInstance {},
	placa: class extends self.ISpriteInstance {},
	balao: class extends self.ISpriteInstance {},
	fonte: class extends self.ISpriteFontInstance {},
	visualLogo: class extends self.ISpriteInstance {},
	balao3: class extends self.ISpriteInstance {},
	balao2: class extends self.ISpriteInstance {},
	BGdialogo2: class extends self.ISpriteInstance {},
	fonte2: class extends self.ISpriteFontInstance {},
	visualLogo2: class extends self.ISpriteInstance {},
	balao4: class extends self.ISpriteInstance {},
	fonte3: class extends self.ISpriteFontInstance {},
	BGdialogo3: class extends self.ISpriteInstance {},
	visualLogo3: class extends self.ISpriteInstance {},
	balao5: class extends self.ISpriteInstance {},
	BGdialogo4: class extends self.ISpriteInstance {},
	fonte4: class extends self.ISpriteFontInstance {},
	visualLogo4: class extends self.ISpriteInstance {},
	balao6: class extends self.ISpriteInstance {},
	BGdialogo5: class extends self.ISpriteInstance {},
	visualLogo5: class extends self.ISpriteInstance {},
	tutorialSuporte: class extends self.ISpriteInstance {},
	fonte5: class extends self.ISpriteFontInstance {},
	tutorialPlataforma: class extends self.ISpriteInstance {},
	balao7: class extends self.ISpriteInstance {},
	BGdialogo6: class extends self.ISpriteInstance {},
	fonte6: class extends self.ISpriteFontInstance {},
	visualLogo6: class extends self.ISpriteInstance {},
	tutorialPlatquebrada: class extends self.ISpriteInstance {},
	balao8: class extends self.ISpriteInstance {},
	BGdialogo7: class extends self.ISpriteInstance {},
	fonte7: class extends self.ISpriteFontInstance {},
	visualLogo7: class extends self.ISpriteInstance {},
	tutorialEquilibrio: class extends self.ISpriteInstance {},
	balao9: class extends self.ISpriteInstance {},
	BGdialogo8: class extends self.ISpriteInstance {},
	fonte8: class extends self.ISpriteFontInstance {},
	visualLogo8: class extends self.ISpriteInstance {},
	balao10: class extends self.ISpriteInstance {},
	BGdialogo9: class extends self.ISpriteInstance {},
	fonte9: class extends self.ISpriteFontInstance {},
	visualLogo9: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	balao11: class extends self.ISpriteInstance {},
	BGdialogo10: class extends self.ISpriteInstance {},
	fonte10: class extends self.ISpriteFontInstance {},
	visualLogo10: class extends self.ISpriteInstance {},
	tutorialChave: class extends self.ISpriteInstance {},
	tutorialAjuda: class extends self.ISpriteInstance {},
	Câmera3D: class extends self.IInstance {},
	coqueiro: class extends self.ISpriteInstance {},
	coqueiroInvertido: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	mato: class extends self.ISpriteInstance {},
	mato2: class extends self.ISpriteInstance {},
	logo: class extends self.ISpriteInstance {},
	logoArara: class extends self.ISpriteInstance {},
	menu2: class extends self.ISpriteInstance {},
	menu1: class extends self.ISpriteInstance {},
	menu3: class extends self.ISpriteInstance {},
	menu4: class extends self.ISpriteInstance {},
	coqueiroInvertido2: class extends self.ISpriteInstance {},
	araraNeymar: class extends self.ISpriteInstance {},
	menuu: class extends self.ISpriteFontInstance {},
	credito: class extends self.ISpriteInstance {},
	FonteDeSprites: class extends self.ISpriteFontInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	creditofinal: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	finaldefase: class extends self.ISpriteFontInstance {},
	salvas: class extends self.ISpriteInstance {},
	FonteDeSprites2: class extends self.ISpriteFontInstance {},
	salvaCommortal: class extends self.ISpriteInstance {},
	salvaFrenter: class extends self.ISpriteInstance {}
}